version: '3.9'

networks:
  qp:
    driver: bridge
    attachable: true

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - qp
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grocery_db
      - PGDATA=/data/postgres

  qp-assesment:
    container_name: qp-assesment
    build: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - qp
    environment:
      - APPLICATION_SERVER_PORT=8080
      - APPLICATION_NAME=grocery-service
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/grocery_db
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_DDL_AUTO=create-drop
