server:
  port: ${APPLICATION_SERVER_PORT:8080}
spring:
  application:
    name: ${APPLICATION_NAME:grocery-service}
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/grocery_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: ${DATASOURCE_DDL_AUTO:create-drop}